---
title: "Week 6 Tasks"
author: "Peter Boyd"
date: "10/31/2018"
output: html_document
---

The data:

```{r, warning = F, message= F, echo=F}
library(tidyverse)
library(here)
whale <- read_csv(here("data", "sperm_whale_pop.csv"))
whale
plot(whale$Year, whale$Population, main = "Population Decline of Sperm Whales", xlab = "Year", ylab = "Populaion")
```

First, we view the plot with the addition of a poisson glm model fitted to the data. 

```{r, warning = F, message= F, echo=F}
glm_model <- glm(whale$Population ~ whale$Year, data = whale, family = "poisson")
summary(glm_model)

# plot(whale$Year, whale$Population, main = "Population Decline of Sperm 
# Whales", xlab = "Year", ylab = "Populaion")
# lines(glm_model$fitted.values)

ggplot(data = whale, aes(x = Year, y = Population)) +
  # geom_pointrange(aes(
  #   ymin = est - 1.96*sd/sqrt(B),
  #   ymax = est + 1.96*sd/sqrt(B))) +
  #   geom_point(size = 0.5) +
  geom_line() +
  geom_smooth(method='glm',formula=y~x, family = "poisson") +
  labs(x = "Year", y = "Population")
```

Simulate for future years

```{r, echo=F, warning=F, message=F}
new_data <- data.frame("Year" = seq(2001, 2050, 1))

preds <- predict(glm_model, newdata = new_data, type = 'response')
```

http://www.columbia.edu/~cjd11/charles_dimaggio/DIRE/resources/R/simRreg.pdf




