---
title: "Week 7 Tasks"
author: "Peter Boyd"
date: "11/9/2018"
output: html_document
---

I'm not sure how well my whale data will work. I think I may have more success with this monarch data that I found. 

https://blog.nwf.org/2017/02/new-numbers-show-monarch-butterfly-populations-still-in-trouble/

http://www.columbia.edu/~cjd11/charles_dimaggio/DIRE/resources/R/simRreg.pdf


```{r}
library(tidyverse)
library(here)
monarch <- read_csv(here("data", "monarch.csv"))
monarch
plot(monarch$Year, monarch$Acres, main = "Population Decline of Monarch Butterflies", xlab = "Year", ylab = "Hectacre Coverage")
```

```{r}
monarch.ts <- as.ts(monarch$Acres)
acf(monarch.ts)
#decompose(monarch.ts)
```

```{r}
pop.decline <- function(df, ntimes){
  fit.poi <- glm(df$Population ~ df$Year, data = df, family = "poisson")
  fit.nb <- glm.nb(df$Population ~ df$Year, data = df)
  #find way to select based on min aic
  n <- length(df$Population)
  X <- cbind(rep(1, n), df$Year)
  b <- coef(fit.nb)
  y.hat <- exp(X %*% b)
  
  coefs <- matrix(ncol = 3, data = rep(0, ntimes*3))
  y.rep <- matrix(ncol = ntimes, data = rpois(n*ntimes, y.hat))
  for (i in 1: ntimes){
    coefs[i, 1] <- summary(lm(y.rep[,i] ~ df$Year))$coefficients[1]
    coefs[i, 2] <- summary(lm(y.rep[,i] ~ df$Year))$coefficients[2]
    coefs[i, 3] <- summary(lm(y.rep[,i] ~ df$Year))$coefficients[3]
  }

  
  new.fit <- colMeans(coefs)[1] + colMeans(coefs)[2]*seq(max(df$Year), max(df$Year) + 50 , 1) + colMeans(coefs)[3]*I(seq(max(df$Year), max(df$Year) + 50 , 1))^2
return(list(colMeans(coefs)))
#yr.extinct <- -colMeans(coefs)[1]/colMeans(coefs)[2]
#return(list(yr.extinct, colMeans(coefs)))
}

pop.decline(df = monarch, ntimes = 100)

ggplot(data = monarch, aes(x = Year, y = Population)) +
  geom_line() +
  geom_smooth (aaa) +
  #geom_smooth(method='glm',formula=y~x, family = "poisson") +
  labs(x = "Year", y = "Population")
```

```{r, message=F, warning=F}
library(MASS)

```


