---
title: "Week Nine Tasks"
author: "Peter Boyd"
date: "11/19/2018"
output: html_document
---


```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(MASS)
library(broom)
whale <- read_csv(here("data", "sperm_whale_pop.csv"))
#monarch <- read_csv(here("data", "monarch.csv"))
addax <- read_csv(here("data", "addax.csv"))
grizzly_ukraine <- read_csv(here("data", "grizzly_ukraine.csv"))
ringed_seal <- read_csv(here("data", "ringed_seal_finland.csv"))
```

```{r, echo = FALSE}

pop.decline <- function(df, ntimes){
  df <- na.omit(df)
  glm.fit <- glm(df$Population ~ df$Year, data = df)
  fit.poi <- glm(df$Population ~ df$Year, data = df, family = "poisson")
  fit.nb <- glm.nb(df$Population ~ df$Year, data = df)
  fits <- list((glm.fit), (fit.poi), (fit.nb))
  #lm.fit <- lm(log(Population) ~ log(Year), data = df)
  
  #compare AIC
  mods <- c("Linear Model", "Poisson", "Negative Binomial")
  aics <- c(summary(glm.fit)$aic, summary(fit.poi)$aic, summary(fit.nb)$aic)
  best_model <- fits[[order(aics)[1]]]
  aic_summary <- cat("AIC for Each Model", "\n",
               mods[1], ": ", aics[1], "\n", 
               mods[2], ": ", aics[2], "\n",
               mods[3], ": ", aics[3], "\n")
  
  
  # do simulation for lowest aic
  n <- max(df$Year) - min(df$Year) +1
  y.hat <- best_model$fitted.values
  
  if(order(aics)[1] == 2){
    y.rep <- matrix(ncol = ntimes, data = c(rpois(n*ntimes, y.hat)))
  } else if(order(aics)[1] == 3){
    y.rep <- matrix(ncol = ntimes, data = c(rnegbin(n = n*ntimes, mu = y.hat, 
                  theta = summary(fit.nb)$theta)))
  } else {
    new_data <- data.frame("Year" = seq(max(df$Year)+1, max(df$Year) + n*ntimes, 1))
    preds <- predict(glm.fit, newdata = new_data, type = 'response')
    preds <- preds + runif(n = n*ntimes, min = min(glm.fit$residuals), max =  
              max(glm.fit$residuals))
    y.rep <- matrix(ncol = ntimes, data = preds)
  }
    
  years <- c(min(df$Year):max(df$Year))
  y.rep.sort <- -apply(-y.rep, 2, sort)
  y.coefs <- t(apply(y.rep.sort, 2, function(y.col) lm(y.col~years)$coef))
  end.dates <- -y.coefs[,1] / y.coefs[,2]
  end.date <- cat("Predicted Extinction: ", mean(end.dates))
  
  #show plot with each model fit
  plot1 <- ggplot(data = df, aes(x = Year, y = Population)) +
  geom_point() +
  geom_smooth(method='glm',formula=y~x, method.args = list(family = "poisson"), 
                 aes(color = "Poisson")) +
  geom_smooth(method='glm',formula=y~x, aes(color = "Linear")) + 
  geom_smooth(method='glm.nb',formula=y~x, aes(color = "Negative Binomial")) +
  scale_colour_manual(name="legend", values=c("orange", "green", "purple")) +
  labs(x = "Year", y = "Population")
  
  #show residual plot for lowest aic model
  aug.best_model <- augment(best_model)
  resid.plot1 <- ggplot(aug.best_model, aes(x = .fitted, y = .resid)) +
    geom_point()
  
  #return stuff
  both_plots <- list(plot1, resid.plot1)
  par(mfrow = c(1,2))
  structure(list(aic_summary, end.date, both_plots))
  #structure(list(plot1, resid.plot1))
}
```


```{r}
pop.decline(df = whale, ntimes = 100)
# pop.decline(df = addax, ntimes = 100)
# pop.decline(df = grizzly_ukraine, ntimes = 100)
# pop.decline(df = ringed_seal, ntimes = 100)
```




```{r, eval = FALSE, include=FALSE}

  if(class(df$Population) == "numeric"){
    glm.fit <- glm(df$Population ~ df$Year, data = df)
    fit.exp <- glm(df$Population ~ df$Year, data = df, family = "Gamma")
    #fit.beta <- glm(df$Population ~ df$Year, data = df, family = "beta")
    
    lm.fit <- lm(log(Population) ~ log(Year), data = df)
    #nls.fit <- nls(Population ~ b0*Year^b1, 
    #data = df, start = list(b0 = exp(coef(lm.fit)[1]), b1 = coef(lm.fit)[2]))
  
  #compare AIC
  mods <- c("Linear Model", "Exponential", "Nonlinear Least Squares")
  aics <- c(summary(glm.fit)$aic, summary(fit.exp)$aic)#, summary(nls.fit)$aic)
  aic_summary <- cat(mods, "\n", aics)
  
  #show plot with each model fit
  plot1 <- ggplot(data = df, aes(x = Year, y = Population)) +
  geom_point() +
  # geom_smooth (method = "nls",
  #             formula = y ~ b0*x^b1, 
  #   data = monarch, start = c(b0 = exp(coef(lm.fit)[1]), b1 = coef(lm.fit)[2]), color = "yellow") +
  #geom_smooth(method='glm',formula=y~x, method.args = list(family = "Gamma"), color = "orange") +
  geom_smooth(method='glm',formula=y~x, color = "purple") + 
  #geom_smooth(method='glm.nb',formula=y~x, color = "green")
  labs(x = "Year", y = "Population") 
  
  #simulation
  y.hat <- fit.poi$fitted.values
  y.rep <- matrix(ncol = ntimes, data = rep(rpois(n*ntimes, y.hat)))
  sim_reg <- lm(sort(y.rep[,100], decreasing = TRUE) ~
                  c(min(whale$Year):max(df$Year)))
  end_date <- -1*summary(sim_reg)$coefficients[1,1] /   
    summary(sim_reg)$coefficients[2,1]
  
  structure(list(aic_summary))
  return(list(plot1))
  }
}
```



```{r, eval = FALSE, include = FALSE}
#add simulation component
#this is basic structure, should incorporate into the function
ntimes <- 100
n <- length(whale$Population)
#X <- cbind(rep(1, n), whale$Year)
#b <- coef(fit.poi)
y.hat <- fit.poi$fitted.values
y.rep <- matrix(ncol = ntimes, data = rep(rpois(n*ntimes, y.hat)))
s.y.rep <- y.rep[do.call(order, as.data.frame(y.rep, header = FALSE)),]
plot(sort(s.y.rep[,100], decreasing = TRUE))
sim_reg <- lm(sort(y.rep[,100], decreasing = TRUE) ~ c(min(whale$Year):max(df$Year)))
end_date <- -1*summary(sim_reg)$coefficients[1,1] / summary(sim_reg)$coefficients[2,1] 



  # end_dates <- double(ntimes)
  # for (i in 1:ntimes){
  #   sim_reg <- lm(sort(y.rep[,i], decreasing = TRUE) ~
  #                 years)
  #   
  #   end_dates[i] <- -1*summary(sim_reg)$coefficients[1,1] /   
  #      summary(sim_reg)$coefficients[2,1]
  # }
  # end_date <- cat("Predicted Extinction: ", mean(end_dates))
}
```

