---
title: "Week 6 Tasks"
author: "Peter Boyd"
date: "10/31/2018"
output: html_document
---

The data:

```{r, warning = F, message= F, echo=F}
library(tidyverse)
library(here)
whale <- read_csv(here("data", "sperm_whale_pop.csv"))
#whale
plot(whale$Year, whale$Population, main = "Population Decline of Sperm Whales", xlab = "Year", ylab = "Populaion")
```

First, we view the plot with the addition of a poisson glm model fitted to the data. 

```{r, warning = F, message= F, echo=F}
fit.poi <- glm(whale$Population ~ whale$Year, data = whale, family = "poisson")
#fit.poi.log <- glm(whale$Population ~ log(whale$Year), data = whale, family = "poisson"(link = "logit"))
#fit.poi.prob <- glm(whale$Population ~ whale$Year, data = whale, family = "poisson"(link = "probit"))

#c(summary(fit.poi)$aic, summary(fit.poi.log)$aic, summary(fit.poi.prob)$aic)
#fit.bin <- glm(whale$Population ~ whale$Year, data = whale, family = "binomial")
#summary(fit.bin)

ntimes <- 100
n <- length(whale$Population)
X <- cbind(rep(1, n), whale$Year)
b <- coef(fit.poi)
y.hat <- fit.poi$fitted.values #exp(X %*% b)

coefs <- matrix(ncol = 2, data = rep(0, ntimes*2))
y.rep <- matrix(ncol = ntimes, data = rep(rpois(n*ntimes, y.hat)))
for (i in 1: ntimes){
  coefs[i, 1] <- summary(lm(y.rep[,i] ~ whale$Year))$coefficients[1]
  coefs[i, 2] <- summary(lm(y.rep[,i] ~ whale$Year))$coefficients[2]
}

colMeans(coefs)
new.fit <- colMeans(coefs)[1] + colMeans(coefs)[2]*seq(max(whale$Year), max(whale$Year) + 50 , 1)

-colMeans(coefs)[1]/colMeans(coefs)[2] # year at which population will be zero






#y.rep <- rpois(n*ntimes, y.hat)
#y.rep.mean <- double(length(y.rep))
#cm <- colMeans(y.rep)
# instead of this, I should average by entry value....then fit those 30 values to a 
#curve? Maybe? but on average, I think this fit is just my inital fit...could be wrong
# from no no no
# I have ntimes different fake data curves. 
# using these ntimes cuves, predit future values...
# this takes care of simulation aspect and predictions. 

#y.rep.mean <- map_dbl(y.rep ~ mean(.[[]]))
# for (i in 1: length(y.rep)){
#   y.rep.mean[i] <- mean(y.rep[[i]])
# }







pop.decline <- function(df, ntimes){
  fit.poi <- glm(df$Population ~ df$Year, data = df, family = "poisson")
  n <- length(df$Population)
  X <- cbind(rep(1, n), df$Year)
  b <- coef(fit.poi)
  y.hat <- exp(X %*% b)
  
  y.rep <- rerun(ntimes, rpois(n, y.hat))
  y.rep.mean <- map_dbl(y.rep[[]] ~ mean(.))
}

#pop.decline(df = whale, ntimes = 100)

ggplot(data = whale, aes(x = Year, y = Population)) +
  geom_line() +
  geom_smooth(method='glm',formula=y~x, family = "poisson") +
  labs(x = "Year", y = "Population")
```

Use prediction for future years. This does not constitute simuation, just a sneak peak at prediction ideas. 

```{r, echo=F, warning=F, message=F}
# new_data <- data.frame("Year" = seq(2001, 2050, 1))
# preds <- predict(glm_model, newdata = new_data, type = 'response')
# plot(preds)
```

```{r}

```







http://www.columbia.edu/~cjd11/charles_dimaggio/DIRE/resources/R/simRreg.pdf

Time Series

```{r}
acf(whale)
acf(whale$Population)

```

