---
title: "Week Eight Tasks"
author: "Peter Boyd"
date: "11/16/2018"
output:
  pdf_document: default
  html_document: default
---

```{r}
# Add if statements to separate cts and discrete data
#xx for discrete, we'll do classic glm, poi, nb, nls
# for cts, we'll do classic glm, exp, beta
# may be helpful to export:
#   plot with each fit
#xx   aic values
#   residual plots
#   maybe make reco based on aic, subjective
library(tidyverse)
library(here)
library(MASS)
whale <- read_csv(here("data", "sperm_whale_pop.csv"))
monarch <- read_csv(here("data", "monarch.csv"))
```

```{r}
#if(class(df$Population) == "integer"){

pop.decline.dis <- function(df, ntimes){
  
  glm.fit <- glm(df$Population ~ df$Year, data = df)
  fit.poi <- glm(df$Population ~ df$Year, data = df, family = "poisson")
  fit.nb <- glm.nb(df$Population ~ df$Year, data = df)
  fits <- list((glm.fit), (fit.poi), (fit.nb))
  lm.fit <- lm(log(Population) ~ log(Year), data = df)
  #nls.fit <- nls(Population ~ b0*Year^b1, 
    #data = df, start = list(b0 = exp(coef(lm.fit)[1]), b1 = coef(lm.fit)[2]))
  
  #compare AIC
  mods <- c("Linear Model", "Poisson", "Negative Binomial")
  aics <- c(summary(glm.fit)$aic, summary(fit.poi)$aic, summary(fit.nb)$aic)
  #aic_summary <- cat(mods, "\n", aics)
  aic_summary <- cat("AIC for Each Model", "\n",
               mods[1], ": ", aics[1], "\n", 
               mods[2], ": ", aics[2], "\n",
               mods[3], ": ", aics[3], "\n")
  
  #show plot with each model fit
  plot1 <- ggplot(data = df, aes(x = Year, y = Population)) +
  geom_point() +
  #geom_smooth (method = "nls",
   #            formula = y ~ b0*x^b1, 
    #data = monarch, start = c(b0 = exp(coef(lm.fit)[1]), b1 = coef(lm.fit)[2]), color = "yellow") +
  geom_smooth(method='glm',formula=y~x, method.args = list(family = "poisson"), color = "orange") +
  geom_smooth(method='glm',formula=y~x, color = "purple") + 
  geom_smooth(method='glm.nb',formula=y~x, color = "green")
  labs(x = "Year", y = "Population")
  
  #show residual plots
  resid.plot1 <- plot(glm.fit$residuals)
  resid.plot2 <- plot(fit.poi$residuals)
  resid.plot3 <- plot(fit.nb$residuals)
  
  # do simulation for lowest aic
  best_model <- fits[[order(aics)[1]]]
  n <- length(df$Population)
  y.hat <- best_model$fitted.values
  #if(order(aics)[1] == 1){
    y.rep <- matrix(ncol = ntimes, data = c(rpois(n*ntimes, y.hat)))
    years <- c(min(df$Year):max(df$Year))
    
    end_dates <- double(ntimes)
    for (i in 1:ntimes){
      sim_reg <- lm(sort(y.rep[,i], decreasing = TRUE) ~
                  years)
    
      end_dates[i] <- -1*summary(sim_reg)$coefficients[1,1] /   
         summary(sim_reg)$coefficients[2,1]
    }
    end_date <- cat("Predicted Extinction: ", mean(end_dates))
    
    
  # }
  # else if(order(aics)[2] == 1){
  #   y.rep <- matrix(ncol = ntimes, data = rep(rpois(n*ntimes, y.hat)))
  # }
  # else{
  #   y.rep <- matrix(ncol = ntimes, data = rep(rpois(n*ntimes, y.hat)))
  # }
  
  #return stuff
  structure(list(aic_summary, end_date))
  #structure(list("Predicted Extinction Date: ", end_date))
  #par(mfrow = c(2,2))
  #structure(list("predicted extinction: " , end_date))
  return(list(plot1, resid.plot1, resid.plot2, resid.plot3))
  #structure(list("Predicted Extinction Date: ", end_date))
  
}
```







```{r, eval = FALSE}

  if(class(df$Population) == "numeric"){
    glm.fit <- glm(df$Population ~ df$Year, data = df)
    fit.exp <- glm(df$Population ~ df$Year, data = df, family = "Gamma")
    #fit.beta <- glm(df$Population ~ df$Year, data = df, family = "beta")
    
    lm.fit <- lm(log(Population) ~ log(Year), data = df)
    #nls.fit <- nls(Population ~ b0*Year^b1, 
    #data = df, start = list(b0 = exp(coef(lm.fit)[1]), b1 = coef(lm.fit)[2]))
  
  #compare AIC
  mods <- c("Linear Model", "Exponential", "Nonlinear Least Squares")
  aics <- c(summary(glm.fit)$aic, summary(fit.exp)$aic)#, summary(nls.fit)$aic)
  aic_summary <- cat(mods, "\n", aics)
  
  #show plot with each model fit
  plot1 <- ggplot(data = df, aes(x = Year, y = Population)) +
  geom_point() +
  # geom_smooth (method = "nls",
  #             formula = y ~ b0*x^b1, 
  #   data = monarch, start = c(b0 = exp(coef(lm.fit)[1]), b1 = coef(lm.fit)[2]), color = "yellow") +
  #geom_smooth(method='glm',formula=y~x, method.args = list(family = "Gamma"), color = "orange") +
  geom_smooth(method='glm',formula=y~x, color = "purple") + 
  #geom_smooth(method='glm.nb',formula=y~x, color = "green")
  labs(x = "Year", y = "Population") 
  
  #simulation
  y.hat <- fit.poi$fitted.values
  y.rep <- matrix(ncol = ntimes, data = rep(rpois(n*ntimes, y.hat)))
  sim_reg <- lm(sort(y.rep[,100], decreasing = TRUE) ~
                  c(min(whale$Year):max(df$Year)))
  end_date <- -1*summary(sim_reg)$coefficients[1,1] /   
    summary(sim_reg)$coefficients[2,1]
  
  structure(list(aic_summary))
  return(list(plot1))
  }
}
```

```{r}
pop.decline.dis(df = whale, ntimes = 100)
#pop.decline.dis(df = monarch, ntimes = 100)
```

```{r, eval = FALSE}
#add simulation component
#this is basic structure, should incorporate into the function
ntimes <- 100
n <- length(whale$Population)
#X <- cbind(rep(1, n), whale$Year)
#b <- coef(fit.poi)
y.hat <- fit.poi$fitted.values
y.rep <- matrix(ncol = ntimes, data = rep(rpois(n*ntimes, y.hat)))
s.y.rep <- y.rep[do.call(order, as.data.frame(y.rep, header = FALSE)),]
plot(sort(s.y.rep[,100], decreasing = TRUE))
sim_reg <- lm(sort(y.rep[,100], decreasing = TRUE) ~ c(min(whale$Year):max(df$Year)))
end_date <- -1*summary(sim_reg)$coefficients[1,1] / summary(sim_reg)$coefficients[2,1] 

}
```

