---
title: "Seal only output"
author: "Peter Boyd"
date: "11/27/2018"
output: html_document
---

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(here)
library(MASS)
library(broom)
library(rsample)
whale <- read_csv(here("data", "sperm_whale_pop.csv"))
#monarch <- read_csv(here("data", "monarch.csv"))
addax <- read_csv(here("data", "addax.csv"))
grizzly_ukraine <- read_csv(here("data", "grizzly_ukraine.csv"))
ringed_seal <- read_csv(here("data", "ringed_seal_finland.csv"))
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}

pop.decline <- function(df, ntimes){
  
  # remove NA values, fit several models
  df <- na.omit(df)
  fit.glm <- glm(df$Population ~ df$Year, data = df)
  fit.poi <- glm(df$Population ~ df$Year, data = df, family = "poisson")
  fit.nb <- glm.nb(df$Population ~ df$Year, data = df)
  #fit.log <- glm(Population ~ log(Year), data = df)
  fits <- list((fit.glm), (fit.poi), (fit.nb))
  #lm.fit <- lm(log(Population) ~ log(Year), data = df)
  #####
  
  #compare AIC of each model and return as a list
  mods <- c("Linear Model", "Poisson", "Negative Binomial")
  aics <- c(summary(fit.glm)$aic, summary(fit.poi)$aic, summary(fit.nb)$aic)
  best_model <- fits[[order(aics)[1]]]
  aic_summary <- cat("AIC for Each Model", "\n",
               mods[1], ": ", aics[1], "\n", 
               mods[2], ": ", aics[2], "\n",
               mods[3], ": ", aics[3], "\n")
  #####
  
  # identify the fit of the best model, use this fit to 
  # simulate data from this fit ntimes
  # sort each of the simulated data
  # regress over each simulation to find predicted extinction date
  # old way, think it is wrong n <- max(df$Year) - min(df$Year) +1
  n <- nrow(df)
  y.hat <- best_model$fitted.values
  
  if(order(aics)[1] == 2){
    y.rep <- matrix(ncol = ntimes, data = c(rpois(n*ntimes, y.hat)))
  } else if(order(aics)[1] == 3){
    y.rep <- matrix(ncol = ntimes, data = c(rnegbin(n = n*ntimes, mu = y.hat, 
                  theta = summary(fit.nb)$theta)))
  } else {
    new_data <- data.frame("Year" = seq(max(df$Year)+1, max(df$Year) + n*ntimes, 1))
    preds <- predict(fit.glm, newdata = new_data, type = 'response')
    preds <- preds + runif(n = n*ntimes, min = min(fit.glm$residuals), max =  
              max(fit.glm$residuals))
    y.rep <- matrix(ncol = ntimes, data = preds)
  }
    
  years <- c(min(df$Year):max(df$Year))
  y.rep.sort <- -apply(-y.rep, 2, sort)
  # y.coefs <- t(apply(y.rep.sort, 2, function(y.col) lm(y.col~years)$coef))
  # end.dates <- -y.coefs[,1] / y.coefs[,2]
  # end.date <- cat("Predicted Extinction: ", mean(end.dates))
  #####
  
   #try to use more rigorous approach to simulate extinction date
  df1 <- df
  pop <- df1$Population[n]
  y.rep.sort1 <- y.rep.sort
  for(j in 1: 15){
    fitted.pred <- double(ntimes)
    fitted.rep <- vector("list", ntimes)
    for(i in 1:ntimes){
      fitted.rep[[i]] <- glm(y.rep.sort1[,i] ~ df1$Year)
      fitted.pred[i] <- predict(fitted.rep[[i]], data.frame(Year = max(df$Year), type = "response"))
    }
    y.rep.sort1 <- rbind(y.rep.sort1, fitted.pred)
    df1[nrow(df1) + 1,] <- c(df1[nrow(df1),1] + 1, round(mean(y.rep.sort1[nrow(y.rep.sort1),])))
    pop <- df1$Population[nrow(df1)]
    j <- j + 1
  }
  end.date.sim <- cat("Second Predicted Extinction: ", df[nrow(df),1])
  #####
  
  
  #create plot with each model fit
  plot1 <- ggplot(data = df, aes(x = Year, y = Population)) +
  geom_point() +
  geom_smooth(method='glm',formula=y~x, method.args = list(family = "poisson"), 
                 aes(color = "Poisson")) +
  geom_smooth(method='glm',formula=y~x, aes(color = "Linear")) + 
  geom_smooth(method='glm.nb',formula=y~x, aes(color = "Neg.Bi")) +
  #geom_smooth(method='glm',formula=y~log(x), aes(color = "Log.Trans")) +
  #geom_jitter(
   # position = position_jitter(width = 0.5, height = 0.5)) + 
  scale_colour_manual(name="legend", values=c("orange", "green", "purple"))
  + labs(x = "Year", y = "Population")
  #####
  
  #create residual plot for lowest aic model
  aug.best_model <- augment(best_model)
  resid.plot1 <- ggplot(aug.best_model, aes(x = .fitted, y = .resid)) +
    geom_point()
  #####
  
  #wrap plots together
  print_plots <- function(x, y){
    {par(mfrow = c(1,2))
    print(x)
    print(y)}
  }
  #####
  
 
  
  #return list of aics, extinction date, plot of fits, residual plot
  return(list(aic_summary,  end.date.sim, print_plots(plot1, resid.plot1)))
}
```


```{r, , fig.height=5, fig.width=4.5, warning=FALSE, message = FALSE}
# pop.decline(df = whale, ntimes = 100)
# pop.decline(df = addax, ntimes = 100)
# pop.decline(df = grizzly_ukraine, ntimes = 100)
pop.decline(df = ringed_seal, ntimes = 100)
```